# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-01 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0002_box_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='contents',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='box',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
